# Generated by Django 4.0.6 on 2022-09-23 11:57

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import player.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, max_length=256, unique=True)),
                ('station_frequency', models.FloatField(unique=True)),
                ('station_url', models.CharField(blank=True, max_length=1023)),
                ('station_cover', models.ImageField(blank=True, upload_to=player.models.Station_Cover_Images, validators=[core.validators.validate_image_extension])),
                ('station_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('encoder_FUI', models.CharField(blank=True, max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FavouritesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_FUI', models.CharField(blank=True, max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.radiostationmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
